// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Retrieves the exact dates of Catholic sacraments using AI.
 *
 * - findSacramentDate - A function that finds the date of a specified sacrament.
 * - FindSacramentDateInput - The input type for the findSacramentDate function.
 * - FindSacramentDateOutput - The return type for the findSacramentDate function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FindSacramentDateInputSchema = z.object({
  name: z.string().describe('The full name of the individual.'),
  approximateYear: z.string().describe('The approximate year the sacrament was received.'),
  location: z.string().describe('The location where the sacrament was received (e.g., church name, city).'),
  sacramentType: z.enum(['Baptism', 'First Communion', 'Confirmation']).describe('The type of sacrament.'),
});
export type FindSacramentDateInput = z.infer<typeof FindSacramentDateInputSchema>;

const FindSacramentDateOutputSchema = z.object({
  sacramentDate: z.string().describe('The exact date the sacrament was received, in YYYY-MM-DD format.'),
  confidenceLevel: z.number().describe('A number between 0 and 1 indicating the confidence level of the date found.'),
});
export type FindSacramentDateOutput = z.infer<typeof FindSacramentDateOutputSchema>;

export async function findSacramentDate(input: FindSacramentDateInput): Promise<FindSacramentDateOutput> {
  return findSacramentDateFlow(input);
}

const findSacramentDatePrompt = ai.definePrompt({
  name: 'findSacramentDatePrompt',
  input: {schema: FindSacramentDateInputSchema},
  output: {schema: FindSacramentDateOutputSchema},
  prompt: `You are an AI assistant specialized in finding exact dates of Catholic sacraments.
  Given the following information, find the exact date the sacrament was received. Respond in YYYY-MM-DD format.
  If the exact date cannot be determined, provide your best estimate and a confidence level.

  Name: {{{name}}}
  Approximate Year: {{{approximateYear}}}
  Location: {{{location}}}
  Sacrament Type: {{{sacramentType}}}

  Output the date in YYYY-MM-DD format and provide a confidence level between 0 and 1.
  If the date cannot be found, set sacramentDate to "Unknown" and the confidenceLevel to 0.
  `,
});

const findSacramentDateFlow = ai.defineFlow(
  {
    name: 'findSacramentDateFlow',
    inputSchema: FindSacramentDateInputSchema,
    outputSchema: FindSacramentDateOutputSchema,
  },
  async input => {
    const {output} = await findSacramentDatePrompt(input);
    return output!;
  }
);
